## -----------------------------------------------
## $HOME/.xsession from Thinkpad T60 - OpenBSD 6.6
## -----------------------------------------------

export ENV=$HOME/.kshrc

## Load X Window configurations
/usr/X11R6/bin/xrdb $HOME/.Xresources

## Sets the "wallpaper" as plain vanilla grey
## xsetroot -solid grey &

## Sets the "wallpaper" as a grey/ black/ white twatch
## xsetroot -gray &

xsetroot -cursor_name left_prt &
xclock -geometry 230x20-0-0 -fn 9x15 -strftime "%A %d %b %Y %H:%M" &

###################
## Window Managers:
###################

## Calm Window Manager
exec cwm

## Tab Window Manager
## twm

########
## XFCE:
########
## exec ck-launch-session startxfce4

## EoF ##
